; Script generated by Inno Setup Script Wizard.
; PC Voice Agent Windows Installer Configuration (TASK-8.4)

#define MyAppName "PC Voice Agent"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "PC Voice Agent Team"
#define MyAppURL "https://github.com/blcoded/pc-agent"
#define MyAppExeName "PCVoiceAgent.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{8B8B5B11-13E0-4E87-A17D-3D4166E7C4F1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Output installer settings
OutputDir=..\dist\installer
OutputBaseFilename=PCVoiceAgent_Setup_1.0.0
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
; Terminate previous running instance before upgrading
CloseApplications=yes
RestartApplications=no
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Launch PC Voice Agent automatically when Windows starts"; GroupDescription: "Windows Integration:"

[Files]
; Dist folder contents built by PyInstaller
Source: "..\dist\PCVoiceAgent\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "--tray"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "--tray"; Tasks: desktopicon

[Registry]
; Configure optional run at Windows startup
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "PCVoiceAgent"; ValueData: """{app}\{#MyAppExeName}"" --tray"; Flags: uninsdeletevalue; Tasks: startup

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Parameters: "--tray"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up runtime caches while preserving user config in AppData
Type: files; Name: "{app}\*.log"
Type: filesandordirs; Name: "{app}\__pycache__"
